spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://svc.sel3.cloudtype.app:31421/host
    username: root
    password: 1234
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 09729369494d098558a6bbda51ec4a30
            client-secret: AM3JmxHxORl09cccmqajgi6NZo80Oz0W
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000/klogin
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
       format-sql: true
       show-sql: true
       use-sql-comments: true
       
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: ERROR

server:
  port: 8090
  servlet:
    session:
      cookie:
        same-site: LAX
        secure: true
        http-only: true
        domain: localhost
        
jwt:
  secret: alsajfleoajflaosemfaosemfQkrQkrdlqkrtncuwhwhffuwnrrpTsp
        
        